### ISSUE TITLE
Update membership status on subscription status change

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-restrict-content-pro#13]
If the Pronamic Pay subscription status changes, this doesn't update the membership status in Restrict Content Pro. A chargeback results in the subscription status being put to 'On Hold', but this is for example not reflected in the RCP membership.

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2519635424/26936_

**Comment by remcotolsma** [comment]
Added some feedback in https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/commit/7fe693819524ac32a81daa5a40280f92b0accb39.

**Comment by rvdsteege** [comment]
Made some changes in https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/compare/7fe6938…43a2db0 and replied in https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/commit/7fe693819524ac32a81daa5a40280f92b0accb39.
