### ISSUE TITLE
Error when using 'Direct Debit (mandate via X)' payment method without auto renewal

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-restrict-content-pro#3]
When using the **Direct Debit (mandate via iDEAL/Bancontact/SOFORT)** payment methods without auto renew, then the first payment will fail with this (Mollie) error:

> Unprocessable Entity - The payment method is not activated on your account.

Instead, the regular iDEAL/Bancontact/SOFORT payment methods can be used both with and without auto renew:
- https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/commit/0456bb58419665e54934589583044790dd775875#diff-da93ebacf7f0dab5d7c471c91f0e17ae0392749606fd28497fe3391b2b42f875

Without auto renew, there is no subscription for the payment, so in the Mollie gateway the sequence type will not be set to `first`:
- https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/blob/develop/src/Util.php#L217-L220
- https://github.com/pronamic/wp-pronamic-pay-mollie/blob/4.0.1/src/Gateway.php#L343-L364

Thoughts, @remcotolsma?

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/1824903680/23725/_

**Comment by remcotolsma** [comment]
For the `pronamic_pay_direct_debit_bancontact `, `pronamic_pay_direct_debit_ideal` and `pronamic_pay_direct_debit_sofort` gateways we should set `mollie_sequence_type` to `first` regardless of `$gateway->auto_renew`?

https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/blob/4332583bee2d4d9849294f562f7322afd414ddfe/src/Extension.php#L209-L211

https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/blob/4332583bee2d4d9849294f562f7322afd414ddfe/src/Gateway.php#L261-L265

In the Mollie library we need to convert the payment method to first with `PaymentMethods::get_first_payment_method( $payment_method ) ` if `'first' === $payment->get_meta( 'mollie_sequence_type' );`? That way, a mandate will be created as the gateway name suggests, but there will be no `auto_renew`.

Or am I missing something @rvdsteege?

**Comment by remcotolsma** [comment]
Or change in Mollie:

```php
if ( \count( $subscriptions ) > 0 ) {
```

to

```php
if (
	\count( $subscriptions ) > 0
		||
	\in_array(
		$payment_method,
		array(
			PaymentMethods::DIRECT_DEBIT_BANCONTACT,
			PaymentMethods::DIRECT_DEBIT_IDEAL,
			PaymentMethods::DIRECT_DEBIT_SOFORT
		),
		true
	)
) {
	
}
```

**Comment by rvdsteege** [comment]
Tested: issue has been resolved in https://github.com/pronamic/wp-pronamic-pay-mollie/pull/3 🎉
